services:
  iec60730-library:
    build:
      context: .
      dockerfile: Dockerfile

    image: iec60730-library:latest
    user: "${DOCKER_UID}:${DOCKER_GID}"
    working_dir: /workspace

    volumes:
      - .:/workspace
      - ${HOME}/.silabs:/home/ubuntu/.silabs

      # Optional Gecko SDK mount
      - ${GSDK_PATH:-/tmp}:/opt/gecko_sdk:ro

    environment:
      SLT_INSTALL_DIR: /home/ubuntu/.silabs
      FLASH_REGIONS_TEST: ${FLASH_REGIONS_TEST}
      SDK_PATH: ${SDK_PATH:-}

    tty: true
