# choose toolchain
if(DEFINED ENV{TOOL_CHAINS})
  set(TOOL_CHAINS "$ENV{TOOL_CHAINS}")
else()
set(TOOL_CHAINS "GCC")
endif()

# Resolve / create user.slconf for SLC/SLT.
# sdk-package-path lists the SDK and this repo (IEC60730 .slce extension),
# which trusts the extension without a separate 'slc signature trust -extpath'.
#
# Path resolution order:
#   1. ENV{SLC_SLCONF} if set (absolute path to an existing .slconf)
#   2. ${CMAKE_SOURCE_DIR}/user.slconf (created/updated from SDK_PATH or GSDK)
#
# Usage: ensure_slc_slconf(<out_var>)
function(ensure_slc_slconf out_var)
  if(DEFINED ENV{SLC_SLCONF} AND EXISTS "$ENV{SLC_SLCONF}")
    set(${out_var} "$ENV{SLC_SLCONF}" PARENT_SCOPE)
    message("-- [I] Using SLC slconf from SLC_SLCONF: $ENV{SLC_SLCONF}")
    return()
  endif()

  set(_slconf "${CMAKE_SOURCE_DIR}/user.slconf")

  if(DEFINED ENV{SDK_PATH} AND NOT "$ENV{SDK_PATH}" STREQUAL "")
    set(_sdk_path "$ENV{SDK_PATH}")
  elseif(DEFINED ENV{GSDK} AND NOT "$ENV{GSDK}" STREQUAL "")
    set(_sdk_path "$ENV{GSDK}")
  elseif(EXISTS "${_slconf}")
    # Keep a pre-existing local file when SDK env vars are unset.
    set(${out_var} "${_slconf}" PARENT_SCOPE)
    message("-- [I] Using existing SLC slconf: ${_slconf}")
    return()
  else()
    message(FATAL_ERROR
      "Cannot create ${_slconf}: set SDK_PATH or GSDK (Simplicity SDK root), "
      "or provide an existing file via SLC_SLCONF.")
  endif()

  string(REGEX REPLACE "/+$" "" _sdk_path "${_sdk_path}")

  file(WRITE "${_slconf}"
"# Auto-generated by CMake for SLC/SLT. Do not commit machine-local paths.
# sdk-package-path trusts the IEC60730 extension (.slce) with the SDK.

[slc]
sdk-package-path = [
  \"${_sdk_path}\",
  \"${CMAKE_SOURCE_DIR}\"
]
")
  set(${out_var} "${_slconf}" PARENT_SCOPE)
  message("-- [I] Generated SLC slconf: ${_slconf}")
  message("-- [I]   SDK: ${_sdk_path}")
  message("-- [I]   Extension: ${CMAKE_SOURCE_DIR}")
endfunction(ensure_slc_slconf)

# SLC CLI 6.x names the generated object library "slc". Rename it to the
# project-specific target name expected by this repo (slc_<project>).
function(rename_slc_generated_target cmake_file new_target_name)
  if(NOT EXISTS "${cmake_file}")
    return()
  endif()
  execute_process(
    COMMAND python3 -c
      "import re, sys\npath, name = sys.argv[1], sys.argv[2]\ntext = open(path, encoding='utf-8').read()\ntext = re.sub(r'(?<![A-Za-z0-9_])slc(?![A-Za-z0-9_])', name, text)\nopen(path, 'w', encoding='utf-8').write(text)"
      "${cmake_file}" "${new_target_name}"
    RESULT_VARIABLE _rename_result
  )
  if(NOT _rename_result EQUAL 0)
    message(FATAL_ERROR "Failed to rename SLC target in ${cmake_file}")
  endif()
endfunction(rename_slc_generated_target)

function(fix_slc_cmake_targets sdk_dir)
  if(${TOOL_CHAINS} STREQUAL "IAR")
    set(_cmake_subdir "cmake_iar")
  else()
    set(_cmake_subdir "cmake_gcc")
  endif()
  set(_cmake_dir "${sdk_dir}/src/${_cmake_subdir}")

  # Primary project (always generated into cmake_gcc / cmake_iar)
  rename_slc_generated_target("${_cmake_dir}/lib_iec60730.cmake" "slc_lib_iec60730")
  rename_slc_generated_target("${_cmake_dir}/CMakeLists.txt" "slc_lib_iec60730")

  # Optional VMC support project (copied aside before primary overwrite)
  set(_vmc_dir "${sdk_dir}/src/lib_iec60730_vmc_support_cmake")
  rename_slc_generated_target("${_vmc_dir}/lib_iec60730_vmc_support.cmake" "slc_lib_iec60730_vmc_support")
  rename_slc_generated_target("${_vmc_dir}/CMakeLists.txt" "slc_lib_iec60730_vmc_support")
endfunction(fix_slc_cmake_targets)

function(generate_lib_iec60730 relative_dir)

    set(FULL_DIR ${CMAKE_SOURCE_DIR}/${relative_dir})

    if(${TOOL_CHAINS} STREQUAL "IAR")
      set(_cmake_subdir "cmake_iar")
    else()
      set(_cmake_subdir "cmake_gcc")
    endif()

    ensure_slc_slconf(SLC_SLCONF)

    if(TEST_SECURE_PERIPHERALS_ENABLE AND ENABLE_INTEGRATION_TESTING)
      execute_process(COMMAND make prepare
        WORKING_DIRECTORY ${FULL_DIR})
      execute_process(COMMAND make vmc_support
        WORKING_DIRECTORY ${FULL_DIR})
    else()
      execute_process(COMMAND make prepare
        WORKING_DIRECTORY ${FULL_DIR})
    endif()

    if(${TOOL_CHAINS} STREQUAL "GCC")
      if(TEST_SECURE_PERIPHERALS_ENABLE AND ENABLE_INTEGRATION_TESTING)
        execute_process(COMMAND slc generate
          --slconf=${SLC_SLCONF}
          -p ${FULL_DIR}/lib_iec60730.slcp
          -np -d ${FULL_DIR}/src -cpproj -name=lib_iec60730_vmc_support -o cmake --with ${BOARD_NAME}
          WORKING_DIRECTORY ${PROJECT_SOURCE_DIR})
        # SLC 6.x always writes cmake_gcc/; preserve VMC project before overwrite
        file(REMOVE_RECURSE ${FULL_DIR}/src/lib_iec60730_vmc_support_cmake)
        file(RENAME ${FULL_DIR}/src/${_cmake_subdir} ${FULL_DIR}/src/lib_iec60730_vmc_support_cmake)
        execute_process(COMMAND slc generate
          --slconf=${SLC_SLCONF}
          -p ${FULL_DIR}/lib_iec60730_secure.slcp
          -np -d ${FULL_DIR}/src -cpproj -name=lib_iec60730 -o cmake --with ${BOARD_NAME}
          WORKING_DIRECTORY ${PROJECT_SOURCE_DIR})
      else()
        execute_process(COMMAND slc generate
          --slconf=${SLC_SLCONF}
          -p ${FULL_DIR}/lib_iec60730.slcp
          -np -cp -d ${FULL_DIR}/src -name=lib_iec60730 -o cmake --with ${BOARD_NAME}
          WORKING_DIRECTORY ${PROJECT_SOURCE_DIR})
      endif()
    elseif (${TOOL_CHAINS} STREQUAL "IAR")
      if(TEST_SECURE_PERIPHERALS_ENABLE AND ENABLE_INTEGRATION_TESTING)
        execute_process(COMMAND slc generate
          --slconf=${SLC_SLCONF}
          -p ${FULL_DIR}/lib_iec60730.slcp
          -np -d ${FULL_DIR}/src -cpproj -name=lib_iec60730_vmc_support -o cmake --with ${BOARD_NAME}
          WORKING_DIRECTORY ${PROJECT_SOURCE_DIR})
        file(REMOVE_RECURSE ${FULL_DIR}/src/lib_iec60730_vmc_support_cmake)
        file(RENAME ${FULL_DIR}/src/${_cmake_subdir} ${FULL_DIR}/src/lib_iec60730_vmc_support_cmake)
        execute_process(COMMAND slc generate
          --slconf=${SLC_SLCONF}
          -p ${FULL_DIR}/lib_iec60730_secure.slcp
          -np -d ${FULL_DIR}/src -cpproj -name=lib_iec60730 -o cmake --with ${BOARD_NAME}
          WORKING_DIRECTORY ${PROJECT_SOURCE_DIR})
        execute_process(COMMAND slc generate
          --slconf=${SLC_SLCONF}
          -p ${FULL_DIR}/lib_iec60730_secure.slcp
          -np -d ${FULL_DIR}/src -cpproj -name=lib_iec60730 -o iar --with ${BOARD_NAME}
          WORKING_DIRECTORY ${PROJECT_SOURCE_DIR})
      else()
        execute_process(COMMAND slc generate
          --slconf=${SLC_SLCONF}
          -p ${FULL_DIR}/lib_iec60730.slcp
          -np -d ${FULL_DIR}/src -cpproj -name=lib_iec60730 -o cmake --with ${BOARD_NAME}
          WORKING_DIRECTORY ${PROJECT_SOURCE_DIR})
        execute_process(COMMAND slc generate
          --slconf=${SLC_SLCONF}
          -p ${FULL_DIR}/lib_iec60730.slcp
          -np -d ${FULL_DIR}/src -cpproj -name=lib_iec60730 -o iar --with ${BOARD_NAME}
          WORKING_DIRECTORY ${PROJECT_SOURCE_DIR})
      endif()
    endif()

    fix_slc_cmake_targets(${FULL_DIR})

    if (EXISTS ${FULL_DIR}/CMakeLists.txt)
        message("-- [I] ${SDK_CMAKE_RELATIVE_DIR} path have CMake File: ${FULL_DIR}/CMakeLists.txt")
        add_subdirectory(${FULL_DIR})
    else()
        message("-- [I] ${SDK_CMAKE_RELATIVE_DIR} path don't have CMake File: ${FULL_DIR}")
    endif()

endfunction(generate_lib_iec60730)
