name: Trigger Workflow Run Unit Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      Branch:
        description: 'branch to checkout'
        required: true
        default: 'main'
jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4.2.2

      - name: Set up environment variables
        run: |
          echo "REPO_B_OWNER=SiliconLabsInternal" >> $GITHUB_ENV
          echo "REPO_B_NAME=DevS-SQA" >> $GITHUB_ENV
          echo "DEFAULT_BRANCH=debug-thvu" >> $GITHUB_ENV
          #echo "Repo_test=${{ github.repository }}" >> $GITHUB_ENV
          echo "Repo_test=SiliconLabsSoftware/IEC60730-Library" >> $GITHUB_ENV
          
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Contribute_branch=${{ github.event.inputs.Branch }}" >> $GITHUB_ENV 
          else
            echo "Contribute_branch=${{ github.head_ref }}" >> $GITHUB_ENV  # PR branch
          fi
          
          echo "Validate_branch=main" >> $GITHUB_ENV
          echo "ADAPTER_SN_MG12=440189400" >> $GITHUB_ENV
          echo "HOST_TP_MG12=192.168.1.118" >> $GITHUB_ENV
          echo "ADAPTER_SN_MG24=440111030" >> $GITHUB_ENV
          echo "HOST_TP_MG24=192.168.1.69" >> $GITHUB_ENV
          echo "RUNNER_BUILD=ubuntu-latest" >> $GITHUB_ENV
          echo "RUNNER_EXECUTE=DS_SQA_HN_01" >> $GITHUB_ENV

      - name: Trigger Workflow
        run: |
          response=$(curl -v -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.SILABS_THIEUVU_PAT }}" \
            -d '{
                  "ref": "refs/heads/${{ env.DEFAULT_BRANCH }}",
                  "inputs": {
                    "Repo_test": "${{ env.Repo_test }}",
                    "Contribute_branch": "${{ env.Contribute_branch }}",
                    "Validate_branch": "${{ env.Validate_branch }}",
                    "ADAPTER_SN_MG12": "${{ env.ADAPTER_SN_MG12 }}",
                    "HOST_TP_MG12": "${{ env.HOST_TP_MG12 }}",
                    "ADAPTER_SN_MG24": "${{ env.ADAPTER_SN_MG24 }}",
                    "HOST_TP_MG24": "${{ env.HOST_TP_MG24 }}"
                    "RUNNER_BUILD": "${{ env.RUNNER_BUILD }}",
                    "RUNNER_EXECUTE": "${{ env.RUNNER_EXECUTE }}"
                  }
                }' \
            https://api.github.com/repos/${{ env.REPO_B_OWNER }}/${{ env.REPO_B_NAME }}/actions/workflows/02-Run_Unit_Test.yaml/dispatches)

          echo "Response: $response"

      - name: Check if Workflow ran successfully
        run: |
          if echo "$response" | grep -q '"message": "Not Found"'; then
            echo "Error: Workflow or repository not found."
            exit 1
          fi
          if echo "$response" | grep -q '"status": "completed"'; then
            echo "Workflow B ran successfully!"
          else
            echo "Workflow B failed to start or complete."
            exit 1
          fi
