name: 01-Generate Firmware Debug
on:
  pull_request:
    branches:
      - 'main'       
  workflow_dispatch:
    inputs:
      branch: 
        description: 'Branch to test'
        type: string
        default: 'dev'
      ADAPTER_SN_MG12: 
        description: 'Adapter serial number of MG12'
        type: string
        default: '440189400'
      ADAPTER_SN_MG24: 
        description: 'Adapter serial number of MG24'
        type: string
        default: '440133193'
    
env:
  AM_CORRETTO_17: https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
  SLC_CLI_URL: https://www.silabs.com/documents/login/software/slc_cli_linux.zip
  COMMANDER_URL: https://www.silabs.com/documents/login/software/SimplicityCommander-Linux.zip
  GCC_URL: https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz
  SIM_REPO: https://github.com/SiliconLabs/simplicity_sdk.git
  GECKO_SDK_REPO: https://github.com/SiliconLabs/gecko_sdk.git
  SDK_VER: v4.4.2
  JLINK_SEGGER_URL: https://www.segger.com/downloads/jlink/JLink_Linux_x86_64.tgz
  TASK: gen-only  
  JLINK_PATH: /opt/SEGGER/JLink/libjlinkarm.so
  REPO_BRANCH: ${{ github.head_ref || github.ref_name }}    
  BOARD_NAME_MG12: brd4161a
  BOARD_NAME_MG24: brd4187c
  ADAPTER_SN_MG12: ${{ github.event.inputs.ADAPTER_SN_MG12 }} #440189400
  ADAPTER_SN_MG24: ${{ github.event.inputs.ADAPTER_SN_MG24 }} #440133193
  HOST_IP: 192.168.1.69
  TOOL_DIRS: arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin
  COMPILER: GCC
  TOOL_CHAINS: GCC
  COMPONENT: all
  CHIP_MG12: EFR32MG12
  CHIP_MG24: EFR32MG24BXXXF1536
jobs:
  job1:
    name: Generate Firmware
    runs-on: [self-hosted, DS_SQA_HN_02]
    permissions:
      contents: read
      pull-requests: write
      
    steps:
    - name: Trigger
      run: |
        echo "Triggered by ${{github.event_name}} event"
        echo "Repo root directory: $GITHUB_WORKSPACE"
        echo "Current directory: $PWD"
    - name: Check Branch Input
      run: |
            if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
              if [ -z "${{ github.event.inputs.branch }}" ]; then
                echo "Branch input is required for manual trigger."
                exit 1
              else
                echo "REPO_BRANCH=${{ github.event.inputs.branch }}">> $GITHUB_ENV
              fi
            fi              
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        ref: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}"
    - name: Log Current Branch and Commit
      run: |
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Current commit: $(git rev-parse HEAD)" 
    
    
    - name: Update package list
      run: |
        sudo apt update -y
        sudo apt upgrade -y
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt update -y
        sudo apt install -y cmake
        cmake --version

